version: '3.4'

services:
  intive.confr.api:
    image: ${DOCKER_REGISTRY:-intiveconfrapi}
    build:
      context: .
      dockerfile: Intive.ConfR.API/Dockerfile

    ports:
      - ${SERVER_PORT}:80

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    depends_on:
      - storage-emulator
      - db

  storage-emulator:
    image: arafato/azurite

  db:
    image: "mcr.microsoft.com/mssql/server"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000"]
      interval: 30s
      timeout: 10s
      retries: 3
