// <auto-generated />
using System;
using Intive.ConfR.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Intive.ConfR.Persistence.Migrations
{
    [DbContext(typeof(ConfRContext))]
    [Migration("20190511114144_CommentsRoom")]
    partial class CommentsRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Intive.ConfR.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CommentID");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnName("Body");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnName("CreatedDateTime");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnName("LastModifiedDateTime");

                    b.Property<string>("RoomId");

                    b.HasKey("CommentId");

                    b.HasIndex("RoomId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Intive.ConfR.Domain.Entities.PhotoUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Intive.ConfR.Domain.Entities.Room", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoomId");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Intive.ConfR.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Intive.ConfR.Domain.Entities.Room", "Room")
                        .WithMany("Comments")
                        .HasForeignKey("RoomId");

                    b.OwnsOne("Intive.ConfR.Domain.ValueObjects.EMailAddress", "RoomEmail", b1 =>
                        {
                            b1.Property<Guid>("CommentId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("RoomEmail");

                            b1.HasKey("CommentId");

                            b1.ToTable("Comments");

                            b1.HasOne("Intive.ConfR.Domain.Entities.Comment")
                                .WithOne("RoomEmail")
                                .HasForeignKey("Intive.ConfR.Domain.ValueObjects.EMailAddress", "CommentId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Intive.ConfR.Domain.Entities.PhotoUrl", b =>
                {
                    b.OwnsOne("Intive.ConfR.Domain.ValueObjects.EMailAddress", "RoomEmail", b1 =>
                        {
                            b1.Property<Guid>("PhotoUrlId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("RoomEmail");

                            b1.HasKey("PhotoUrlId");

                            b1.ToTable("Photos");

                            b1.HasOne("Intive.ConfR.Domain.Entities.PhotoUrl")
                                .WithOne("RoomEmail")
                                .HasForeignKey("Intive.ConfR.Domain.ValueObjects.EMailAddress", "PhotoUrlId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Intive.ConfR.Domain.Entities.Room", b =>
                {
                    b.OwnsOne("Intive.ConfR.Domain.ValueObjects.EMailAddress", "Email", b1 =>
                        {
                            b1.Property<string>("RoomId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("RoomEmail");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.HasOne("Intive.ConfR.Domain.Entities.Room")
                                .WithOne("Email")
                                .HasForeignKey("Intive.ConfR.Domain.ValueObjects.EMailAddress", "RoomId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
